// <auto-generated />
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.

namespace MagicOnion
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::MagicOnion;
    using global::MagicOnion.Client;

    public static partial class MagicOnionInitializer
    {
        static bool isRegistered = false;

        public static void Register()
        {
            if (isRegistered) return;
            isRegistered = true;

            global::MagicOnion.Client.MagicOnionClientFactoryProvider.Default =
                (global::MagicOnion.Client.MagicOnionClientFactoryProvider.Default is global::MagicOnion.Client.ImmutableMagicOnionClientFactoryProvider immutableMagicOnionClientFactoryProvider)
                    ? immutableMagicOnionClientFactoryProvider.Add(MagicOnionGeneratedClientFactoryProvider.Instance)
                    : new global::MagicOnion.Client.ImmutableMagicOnionClientFactoryProvider(MagicOnionGeneratedClientFactoryProvider.Instance);

            global::MagicOnion.Client.StreamingHubClientFactoryProvider.Default =
                (global::MagicOnion.Client.StreamingHubClientFactoryProvider.Default is global::MagicOnion.Client.ImmutableStreamingHubClientFactoryProvider immutableStreamingHubClientFactoryProvider)
                    ? immutableStreamingHubClientFactoryProvider.Add(MagicOnionGeneratedClientFactoryProvider.Instance)
                    : new global::MagicOnion.Client.ImmutableStreamingHubClientFactoryProvider(MagicOnionGeneratedClientFactoryProvider.Instance);
        }
    }

    public partial class MagicOnionGeneratedClientFactoryProvider : global::MagicOnion.Client.IMagicOnionClientFactoryProvider, global::MagicOnion.Client.IStreamingHubClientFactoryProvider
    {
        public static MagicOnionGeneratedClientFactoryProvider Instance { get; } = new MagicOnionGeneratedClientFactoryProvider();

        MagicOnionGeneratedClientFactoryProvider() {}

        bool global::MagicOnion.Client.IMagicOnionClientFactoryProvider.TryGetFactory<T>(out global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T> factory)
            => (factory = MagicOnionClientFactoryCache<T>.Factory) != null;

        bool global::MagicOnion.Client.IStreamingHubClientFactoryProvider.TryGetFactory<TStreamingHub, TReceiver>(out global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver> factory)
            => (factory = StreamingHubClientFactoryCache<TStreamingHub, TReceiver>.Factory) != null;

        static class MagicOnionClientFactoryCache<T> where T : global::MagicOnion.IService<T>
        {
            public readonly static global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T> Factory;

            static MagicOnionClientFactoryCache()
            {
                object factory = default(global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T>);

                if (typeof(T) == typeof(global::HyperEdge.Sdk.Shared.Services.IAccountService))
                {
                    factory = ((global::MagicOnion.Client.MagicOnionClientFactoryDelegate<global::HyperEdge.Sdk.Shared.Services.IAccountService>)((x, y) => new HyperEdge.Sdk.Shared.Services.AccountServiceClient(x, y)));
                }
                if (typeof(T) == typeof(global::HyperEdge.Sdk.Shared.Services.IAuthService))
                {
                    factory = ((global::MagicOnion.Client.MagicOnionClientFactoryDelegate<global::HyperEdge.Sdk.Shared.Services.IAuthService>)((x, y) => new HyperEdge.Sdk.Shared.Services.AuthServiceClient(x, y)));
                }
                if (typeof(T) == typeof(global::HyperEdge.Sdk.Shared.Services.IHealthService))
                {
                    factory = ((global::MagicOnion.Client.MagicOnionClientFactoryDelegate<global::HyperEdge.Sdk.Shared.Services.IHealthService>)((x, y) => new HyperEdge.Sdk.Shared.Services.HealthServiceClient(x, y)));
                }
                Factory = (global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T>)factory;
            }
        }
        
        static class StreamingHubClientFactoryCache<TStreamingHub, TReceiver> where TStreamingHub : global::MagicOnion.IStreamingHub<TStreamingHub, TReceiver>
        {
            public readonly static global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver> Factory;

            static StreamingHubClientFactoryCache()
            {
                object factory = default(global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver>);


                Factory = (global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver>)factory;
            }
        }
    }

}

#pragma warning restore 168
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 612
#pragma warning restore 618

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.
namespace MagicOnion.Resolvers
{
    using global::System;
    using global::MessagePack;

    partial class PreserveAttribute : global::System.Attribute {}
    public class MagicOnionResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new MagicOnionResolver();
    
        MagicOnionResolver() {}
    
        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
            => FormatterCache<T>.formatter;
    
        static class FormatterCache<T>
        {
            public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> formatter;
    
            static FormatterCache()
            {
                var f = MagicOnionResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }
    internal static class MagicOnionResolverGetFormatterHelper
    {
        static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;
    
        static MagicOnionResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(0)
            {
            };
        }
        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }
        
            switch (key)
            {
                default: return null;
            }
        }
    }
    /// <summary>Type hints for Ahead-of-Time compilation.</summary>
    [MagicOnion.Resolvers.Preserve]
    internal static class TypeHints
    {
        [MagicOnion.Resolvers.Preserve]
        internal static void Register()
        {
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.CheckHealthResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.GetLoginChallengeRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.GetRegisterAccountChallengeRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MessagePack.Nil>();
        }
    }
}
#pragma warning restore 168
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 612
#pragma warning restore 618

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.

namespace HyperEdge.Sdk.Shared.Services
{
    using global::System;
    using global::Grpc.Core;
    using global::MagicOnion;
    using global::MagicOnion.Client;
    using global::MessagePack;
    
    [global::MagicOnion.Ignore]
    public class AccountServiceClient : global::MagicOnion.Client.MagicOnionClientBase<global::HyperEdge.Sdk.Shared.Services.IAccountService>, global::HyperEdge.Sdk.Shared.Services.IAccountService
    {
        class ClientCore
        {
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountRequest, global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountResponse> RegisterAccount;
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountRequest, global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountResponse> UpdateAccount;
            public ClientCore(global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider)
            {
                this.RegisterAccount = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountRequest, global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountResponse>(global::Grpc.Core.MethodType.Unary, "IAccountService", "RegisterAccount", serializerProvider);
                this.UpdateAccount = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountRequest, global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountResponse>(global::Grpc.Core.MethodType.Unary, "IAccountService", "UpdateAccount", serializerProvider);
            }
        }
        
        readonly ClientCore core;
        
        public AccountServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider) : base(options)
        {
            this.core = new ClientCore(serializerProvider);
        }
        
        private AccountServiceClient(MagicOnionClientOptions options, ClientCore core) : base(options)
        {
            this.core = core;
        }
        
        protected override global::MagicOnion.Client.MagicOnionClientBase<IAccountService> Clone(global::MagicOnion.Client.MagicOnionClientOptions options)
            => new AccountServiceClient(options, core);
        
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountResponse> RegisterAccount(global::HyperEdge.Sdk.Shared.Protocol.RegisterAccountRequest req)
            => this.core.RegisterAccount.InvokeUnary(this, "IAccountService/RegisterAccount", req);
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountResponse> UpdateAccount(global::HyperEdge.Sdk.Shared.Protocol.UpdateAccountRequest req)
            => this.core.UpdateAccount.InvokeUnary(this, "IAccountService/UpdateAccount", req);
    }
}

namespace HyperEdge.Sdk.Shared.Services
{
    using global::System;
    using global::Grpc.Core;
    using global::MagicOnion;
    using global::MagicOnion.Client;
    using global::MessagePack;
    
    [global::MagicOnion.Ignore]
    public class AuthServiceClient : global::MagicOnion.Client.MagicOnionClientBase<global::HyperEdge.Sdk.Shared.Services.IAuthService>, global::HyperEdge.Sdk.Shared.Services.IAuthService
    {
        class ClientCore
        {
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::HyperEdge.Sdk.Shared.Protocol.GetRegisterAccountChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse> GetRegisterAccountChallenge;
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::HyperEdge.Sdk.Shared.Protocol.GetLoginChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse> GetLoginChallenge;
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeResponse> ValidateChallenge;
            public ClientCore(global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider)
            {
                this.GetRegisterAccountChallenge = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::HyperEdge.Sdk.Shared.Protocol.GetRegisterAccountChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse>(global::Grpc.Core.MethodType.Unary, "IAuthService", "GetRegisterAccountChallenge", serializerProvider);
                this.GetLoginChallenge = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::HyperEdge.Sdk.Shared.Protocol.GetLoginChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse>(global::Grpc.Core.MethodType.Unary, "IAuthService", "GetLoginChallenge", serializerProvider);
                this.ValidateChallenge = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeRequest, global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeResponse>(global::Grpc.Core.MethodType.Unary, "IAuthService", "ValidateChallenge", serializerProvider);
            }
        }
        
        readonly ClientCore core;
        
        public AuthServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider) : base(options)
        {
            this.core = new ClientCore(serializerProvider);
        }
        
        private AuthServiceClient(MagicOnionClientOptions options, ClientCore core) : base(options)
        {
            this.core = core;
        }
        
        protected override global::MagicOnion.Client.MagicOnionClientBase<IAuthService> Clone(global::MagicOnion.Client.MagicOnionClientOptions options)
            => new AuthServiceClient(options, core);
        
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse> GetRegisterAccountChallenge(global::HyperEdge.Sdk.Shared.Protocol.GetRegisterAccountChallengeRequest req)
            => this.core.GetRegisterAccountChallenge.InvokeUnary(this, "IAuthService/GetRegisterAccountChallenge", req);
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.GetChallengeResponse> GetLoginChallenge(global::HyperEdge.Sdk.Shared.Protocol.GetLoginChallengeRequest req)
            => this.core.GetLoginChallenge.InvokeUnary(this, "IAuthService/GetLoginChallenge", req);
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeResponse> ValidateChallenge(global::HyperEdge.Sdk.Shared.Protocol.ValidateChallengeRequest req)
            => this.core.ValidateChallenge.InvokeUnary(this, "IAuthService/ValidateChallenge", req);
    }
}

namespace HyperEdge.Sdk.Shared.Services
{
    using global::System;
    using global::Grpc.Core;
    using global::MagicOnion;
    using global::MagicOnion.Client;
    using global::MessagePack;
    
    [global::MagicOnion.Ignore]
    public class HealthServiceClient : global::MagicOnion.Client.MagicOnionClientBase<global::HyperEdge.Sdk.Shared.Services.IHealthService>, global::HyperEdge.Sdk.Shared.Services.IHealthService
    {
        class ClientCore
        {
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::MessagePack.Nil, global::HyperEdge.Sdk.Shared.Protocol.CheckHealthResponse> CheckHealth;
            public ClientCore(global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider)
            {
                this.CheckHealth = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_ValueType_RefType<global::MessagePack.Nil, global::HyperEdge.Sdk.Shared.Protocol.CheckHealthResponse>(global::Grpc.Core.MethodType.Unary, "IHealthService", "CheckHealth", serializerProvider);
            }
        }
        
        readonly ClientCore core;
        
        public HealthServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider) : base(options)
        {
            this.core = new ClientCore(serializerProvider);
        }
        
        private HealthServiceClient(MagicOnionClientOptions options, ClientCore core) : base(options)
        {
            this.core = core;
        }
        
        protected override global::MagicOnion.Client.MagicOnionClientBase<IHealthService> Clone(global::MagicOnion.Client.MagicOnionClientOptions options)
            => new HealthServiceClient(options, core);
        
        public global::MagicOnion.UnaryResult<global::HyperEdge.Sdk.Shared.Protocol.CheckHealthResponse> CheckHealth()
            => this.core.CheckHealth.InvokeUnary(this, "IHealthService/CheckHealth", global::MessagePack.Nil.Default);
    }
}


#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.


